Repository timemates/app, pull requests merged in 2023-07, with the labels that each got.

#39 feat (#32): authorization screens
  .github/workflows/run-tests-on-pr.yml
  build-plugins/configurations/build.gradle.kts
  feature/authorization/dependencies/src/commonMain/kotlin/io/timemates/app/authorization/dependencies/screens/StartAuthorizationModule.kt
  feature/users/data/database/src/commonMain/sqldelight/io/timemates/app/users/data/database/Users.sq
  gradle/libs.versions.toml
  platforms/android/build.gradle.kts
  platforms/android/src/main/AndroidManifest.xml
  platforms/android/src/main/kotlin/io/timemates/app/TimeMatesApplication.kt
  platforms/desktop/build.gradle.kts
  platforms/desktop/src/main/kotlin/io/timemates/app/Main.kt
  style-system/build.gradle.kts
  ui-core/build.gradle.kts
Labels: feature

#42 feat (#40): added gradle workflow caching
  .github/workflows/run-tests-on-pr.yml
Labels: CI

#45 feat (#34): ui components
  feature/authorization/presentation/src/commonMain/kotlin/io/timemates/app/authorization/ui/confirmation/ConfirmAuthorizationScreen.kt
  feature/authorization/presentation/src/commonMain/kotlin/io/timemates/app/authorization/ui/start/StartAuthorizationScreen.kt
  settings.gradle.kts
  style-system/build.gradle.kts
  style-system/preview/build.gradle.kts
  style-system/preview/src/jvmMain/kotlin/io/timemates/app/style/system/preview/appbar/AppBar.kt
  style-system/preview/src/jvmMain/kotlin/io/timemates/app/style/system/preview/button/Fab.kt
  style-system/src/androidMain/AndroidManifest.xml
  style-system/src/commonMain/kotlin/io/timemates/app/style/system/appbar/AppBar.kt
  style-system/src/commonMain/kotlin/io/timemates/app/style/system/button/Button.kt
  style-system/src/commonMain/kotlin/io/timemates/app/style/system/button/Fab.kt
  style-system/src/commonMain/kotlin/io/timemates/app/style/system/theme/AppColors.kt
  style-system/src/commonMain/kotlin/io/timemates/app/style/system/theme/AppFont.kt
  style-system/src/commonMain/kotlin/io/timemates/app/style/system/theme/AppTheme.kt
  style-system/src/commonMain/kotlin/io/timemates/app/style/system/theme/Color.kt
  style-system/src/commonMain/kotlin/io/timemates/app/style/system/theme/Theme.kt
  style-system/src/commonMain/resources/MR/fonts/Inter-Black.ttf
  style-system/src/commonMain/resources/MR/fonts/Inter-Bold.ttf
  style-system/src/commonMain/resources/MR/fonts/Inter-ExtraBold.ttf
  style-system/src/commonMain/resources/MR/fonts/Inter-ExtraLight.ttf
  style-system/src/commonMain/resources/MR/fonts/Inter-Light.ttf
  style-system/src/commonMain/resources/MR/fonts/Inter-Medium.ttf
  style-system/src/commonMain/resources/MR/fonts/Inter-Regular.ttf
  style-system/src/commonMain/resources/MR/fonts/Inter-SemiBold.ttf
  style-system/src/commonMain/resources/MR/fonts/Inter-Thin.ttf
Labels: feature

#49 feat (#47): shimmer effect for compose
  foundation/shimmer-compose/build.gradle.kts
  foundation/shimmer-compose/src/commonMain/kotlin/io/timemates/app/foundation/shimmer/ShimmerEffect.kt
  settings.gradle.kts
Labels: feature

#53 fix: desktop start
  feature/authorization/presentation/build.gradle.kts
  feature/authorization/presentation/src/commonMain/kotlin/io/timemates/app/authorization/ui/start/StartAuthorizationScreen.kt
  navigation/src/commonMain/kotlin/io/timemates/app/navigation/TimeMatesAppEntry.kt
  platforms/desktop/build.gradle.kts
  platforms/desktop/src/main/kotlin/io/timemates/app/tray/TimeMatesTray.kt
  platforms/desktop/src/main/resources/fonts/Inter-Black.ttf
  platforms/desktop/src/main/resources/fonts/Inter-Bold.ttf
  platforms/desktop/src/main/resources/fonts/Inter-ExtraBold.ttf
  platforms/desktop/src/main/resources/fonts/Inter-ExtraLight.ttf
  platforms/desktop/src/main/resources/fonts/Inter-Light.ttf
  platforms/desktop/src/main/resources/fonts/Inter-Medium.ttf
  platforms/desktop/src/main/resources/fonts/Inter-Regular.ttf
  platforms/desktop/src/main/resources/fonts/Inter-SemiBold.ttf
  platforms/desktop/src/main/resources/fonts/Inter-Thin.ttf
Labels: bug

#54 refactor: desktop
  platforms/desktop/src/main/kotlin/io/timemates/app/AppConstants.kt
  platforms/desktop/src/main/kotlin/io/timemates/app/Dependencies.kt
  platforms/desktop/src/main/kotlin/io/timemates/app/Main.kt
  platforms/desktop/src/main/kotlin/io/timemates/app/Tray.kt
  platforms/desktop/src/main/kotlin/io/timemates/app/UI.kt
  platforms/desktop/src/main/kotlin/io/timemates/app/tray/TimeMatesTray.kt
Labels: refactor

#56 docs&fix: fix link to project in README
  README-uk.md
  README.md
Labels: documentation

#80 tests (#64): implemented for after start
  feature/authorization/presentation/src/jvmTest/kotlin/io/timemates/app/authorization/ui/afterstart/AfterStartReducerTest.kt
Labels: tests

#82 test (#65): write tests for new_account_info
  feature/authorization/presentation/src/jvmTest/kotlin/io/timemates/app/authorization/ui/new_account_info/mvi/NewAccountInfoReducerTest.kt
Labels: tests

#83 feat (#72): `TimersRepository` implementation
  feature/timers/data/build.gradle.kts
  feature/timers/data/src/commonMain/kotlin/io/timemates/app/timers/data/TimersRepository.kt
  feature/timers/dependencies/build.gradle.kts
  feature/timers/dependencies/src/commonMain/kotlin/io/timemates/app/timers/dependencies/TimersDataModule.kt
  feature/timers/domain/src/commonMain/kotlin/io/timemates/app/users/repositories/TimersRepository.kt
  feature/timers/domain/src/commonMain/kotlin/io/timemates/app/users/usecases/GetUserTimersUseCase.kt
  gradle/libs.versions.toml
Labels: feature
